// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV3aV8WEBm2KAkYacgAivkXnNLAxozGKQ',
    appId: '1:487666659299:web:028ff73d155aecc84cfad6',
    messagingSenderId: '487666659299',
    projectId: 'ecommerce-73fbb',
    authDomain: 'ecommerce-73fbb.firebaseapp.com',
    storageBucket: 'ecommerce-73fbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYm23zgrZg7skj8VeR6n8y6wQkPBi1mM',
    appId: '1:487666659299:android:e45d1a0d055488504cfad6',
    messagingSenderId: '487666659299',
    projectId: 'ecommerce-73fbb',
    storageBucket: 'ecommerce-73fbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2a_kOxZVRwTPjPs3y0H3hAmxg_BS9f2s',
    appId: '1:487666659299:ios:e084de4fc2e0085c4cfad6',
    messagingSenderId: '487666659299',
    projectId: 'ecommerce-73fbb',
    storageBucket: 'ecommerce-73fbb.firebasestorage.app',
    iosBundleId: 'com.example.fullEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2a_kOxZVRwTPjPs3y0H3hAmxg_BS9f2s',
    appId: '1:487666659299:ios:edee7f33b65c60924cfad6',
    messagingSenderId: '487666659299',
    projectId: 'ecommerce-73fbb',
    storageBucket: 'ecommerce-73fbb.firebasestorage.app',
    iosBundleId: 'com.example.fullEcommerce.RunnerTests',
  );
}
